[package]
name = "ironboyadvance"
version = "0.1.0"
edition = "2024"
autotests = false

[[test]]
name = "gbc"
path = "tests/gbc.rs"

[[test]]
name = "gba"
path = "tests/gba.rs"

[dependencies]
ironboyadvance_common = { path = "../ironboyadvance_common" }
ironboyadvance_gba = { path = "../ironboyadvance_gba" }
ironboyadvance_gbc = { path = "../ironboyadvance_gbc" }
thiserror = { workspace = true }
