pub const CYCLES_PER_PIXEL: u32 = 4;

pub const HDRAW_PIXELS: u32 = 240;
pub const HBLANK_PIXELS: u32 = 68;

pub const HDRAW_CYCLES: u32 = HDRAW_PIXELS * CYCLES_PER_PIXEL;
pub const HBLANK_CYCLES: u32 = HBLANK_PIXELS * CYCLES_PER_PIXEL;
pub const CYCLES_PER_SCANLINE: u32 = HDRAW_CYCLES + HBLANK_CYCLES;

pub const VDRAW_SCANLINES: u32 = 160;
pub const VBLANK_SCANLINES: u32 = 68;
pub const VDRAW_CYCLES: u32 = VDRAW_SCANLINES * CYCLES_PER_SCANLINE;
pub const VBLANK_CYCLES: u32 = VBLANK_SCANLINES * CYCLES_PER_SCANLINE;

pub const CYCLES_PER_FRAME: usize = VDRAW_CYCLES as usize + VBLANK_CYCLES as usize;
